// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgTXrL8sLmWYXl41QynpmwgWYMRImtdKg',
    appId: '1:107481852070:web:39f7cb762035fb8a562c67',
    messagingSenderId: '107481852070',
    projectId: 'menotes-bc8f8',
    authDomain: 'menotes-bc8f8.firebaseapp.com',
    storageBucket: 'menotes-bc8f8.appspot.com',
    measurementId: 'G-08F9TX5B0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGfYgpdB5Ojv9UJWpcFMkCe0K2lq_QdA',
    appId: '1:107481852070:android:30f84733a97677cb562c67',
    messagingSenderId: '107481852070',
    projectId: 'menotes-bc8f8',
    storageBucket: 'menotes-bc8f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpUsag8F3kNTJ32--SWjHLHdWPUBTqtU',
    appId: '1:107481852070:ios:09616551095f8f27562c67',
    messagingSenderId: '107481852070',
    projectId: 'menotes-bc8f8',
    storageBucket: 'menotes-bc8f8.appspot.com',
    iosClientId:
        '107481852070-3fsabec33qh5t8unhni9n4jtmgfguuk0.apps.googleusercontent.com',
    iosBundleId: 'com.yoop.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpUsag8F3kNTJ32--SWjHLHdWPUBTqtU',
    appId: '1:107481852070:ios:09616551095f8f27562c67',
    messagingSenderId: '107481852070',
    projectId: 'menotes-bc8f8',
    storageBucket: 'menotes-bc8f8.appspot.com',
    iosClientId:
        '107481852070-3fsabec33qh5t8unhni9n4jtmgfguuk0.apps.googleusercontent.com',
    iosBundleId: 'com.yoop.mynotes',
  );
}
